set -g _tide_color_light_blue 00AFFF
set -g _tide_color_light_green 5FAF00
set -g _tide_color_green 5FD700
set -g _tide_color_gold D7AF00
set -g _tide_color_dark_green 2f6b00
set -g _tide_color_dark_blue 9E9EBF
set -g _tide_color_background 303030

set -g tide_aws_bg_color $_tide_color_background
set -g tide_aws_color FF9900
set -g tide_bun_bg_color 14151A
set -g tide_bun_color FBF0DF
set -g tide_character_color $_tide_color_green
set -g tide_character_color_failure FF0000
set -g tide_cmd_duration_bg_color $_tide_color_background
set -g tide_cmd_duration_color 949494
set -g tide_cmd_duration_decimals 0
set -g tide_cmd_duration_threshold 3000
set -g tide_context_always_display false
set -g tide_context_bg_color $_tide_color_background
set -g tide_context_color_default D7AF87
set -g tide_context_color_root $_tide_color_gold
set -g tide_context_color_ssh D7AF87
set -g tide_context_hostname_parts 1
set -g tide_crystal_bg_color $_tide_color_background
set -g tide_crystal_color FFFFFF
set -g tide_direnv_bg_color $_tide_color_background
set -g tide_direnv_bg_color_denied $_tide_color_background
set -g tide_direnv_color $_tide_color_gold
set -g tide_direnv_color_denied FF0000
set -g tide_distrobox_bg_color $_tide_color_background
set -g tide_distrobox_color FF00FF
set -g tide_docker_bg_color $_tide_color_background
set -g tide_docker_color 2496ED
set -g tide_docker_default_contexts default colima
set -g tide_elixir_bg_color $_tide_color_background
set -g tide_elixir_color 4E2A8E
set -g tide_gcloud_bg_color $_tide_color_background
set -g tide_gcloud_color 4285F4
set -g tide_git_bg_color $_tide_color_background
set -g tide_git_bg_color_unstable $_tide_color_background
set -g tide_git_bg_color_urgent $_tide_color_background
set -g tide_git_color_branch ffffff
set -g tide_git_color_conflicted FF0000
set -g tide_git_color_dirty $_tide_color_gold
set -g tide_git_color_operation FF0000
set -g tide_git_color_staged $_tide_color_gold
set -g tide_git_color_stash $_tide_color_green
set -g tide_git_color_untracked $_tide_color_light_blue
set -g tide_git_color_upstream $_tide_color_green
set -g tide_git_truncation_length 24
set -g tide_git_truncation_strategy
set -g tide_go_bg_color $_tide_color_background
set -g tide_go_color 00ACD7
set -g tide_java_bg_color $_tide_color_background
set -g tide_java_color ED8B00
set -g tide_jobs_bg_color $_tide_color_background
set -g tide_jobs_color $_tide_color_dark_green
set -g tide_jobs_number_threshold 1000
set -g tide_kubectl_bg_color $_tide_color_background
set -g tide_kubectl_color 326CE5
set -g tide_left_prompt_frame_enabled true
set -g tide_left_prompt_items pwd git newline
set -g tide_left_prompt_prefix ''
set -g tide_left_prompt_separator_diff_color 
set -g tide_left_prompt_separator_same_color │
set -g tide_left_prompt_suffix ▓▒░
set -g tide_nix_shell_bg_color $_tide_color_background
set -g tide_nix_shell_color 7EBAE4
set -g tide_node_bg_color $_tide_color_background
set -g tide_node_color 44883E
set -g tide_os_bg_color $_tide_color_background
set -g tide_os_color EEEEEE
set -g tide_php_bg_color $_tide_color_background
set -g tide_php_color 617CBE
set -g tide_private_mode_bg_color $_tide_color_background
set -g tide_private_mode_color FFFFFF
set -g tide_prompt_add_newline_before false
set -g tide_prompt_color_frame_and_connection 808080
set -g tide_prompt_color_separator_same_color 808080
set -g tide_prompt_icon_connection ' '
set -g tide_prompt_min_cols 34
set -g tide_prompt_pad_items true
set -g tide_prompt_transient_enabled true
set -g tide_pulumi_bg_color $_tide_color_background
set -g tide_pulumi_color F7BF2A
set -g tide_pwd_bg_color $_tide_color_background
set -g tide_pwd_color_anchors $_tide_color_light_blue
set -g tide_pwd_color_dirs 0087AF
set -g tide_pwd_color_truncated_dirs 0087AF
set -g tide_pwd_markers .bzr .citc .git .hg .node-version .python-version .ruby-version .shorten_folder_marker .svn .terraform bun.lockb Cargo.toml composer.json CVS go.mod package.json build.zig
set -g tide_python_bg_color $_tide_color_background
set -g tide_python_color 00AFAF
set -g tide_right_prompt_frame_enabled true
set -g tide_right_prompt_items status cmd_duration time context jobs direnv bun node python rustc java php pulumi ruby go gcloud kubectl distrobox toolbox terraform aws nix_shell crystal elixir zig newline
set -g tide_right_prompt_prefix ░▒▓
set -g tide_right_prompt_separator_diff_color 
set -g tide_right_prompt_separator_same_color │
set -g tide_right_prompt_suffix ''
set -g tide_ruby_bg_color $_tide_color_background
set -g tide_ruby_color B31209
set -g tide_rustc_bg_color $_tide_color_background
set -g tide_rustc_color F74C00
set -g tide_shlvl_bg_color $_tide_color_background
set -g tide_shlvl_color d78700
set -g tide_shlvl_threshold 1
set -g tide_status_bg_color $_tide_color_background
set -g tide_status_bg_color_failure $_tide_color_background
set -g tide_status_color $_tide_color_light_green
set -g tide_status_color_failure EC7979
set -g tide_status_icon ✔
set -g tide_status_icon_failure ✘
set -g tide_terraform_bg_color $_tide_color_background
set -g tide_terraform_color 844FBA
set -g tide_time_bg_color $_tide_color_background
set -g tide_time_color 5F8787
set -g tide_time_format %T
set -g tide_toolbox_bg_color $_tide_color_background
set -g tide_toolbox_color 613583
set -g tide_vi_mode_bg_color_default $_tide_color_background
set -g tide_vi_mode_bg_color_insert $_tide_color_background
set -g tide_vi_mode_bg_color_replace $_tide_color_background
set -g tide_vi_mode_bg_color_visual $_tide_color_background
set -g tide_vi_mode_color_default 949494
set -g tide_vi_mode_color_insert 87AFAF
set -g tide_vi_mode_color_replace 87AF87
set -g tide_vi_mode_color_visual FF8700
set -g tide_zig_bg_color $_tide_color_background
set -g tide_zig_color F7A41D

set -g fish_color_normal normal
set -g fish_color_command normal
set -g fish_color_keyword normal
set -g fish_color_quote normal
set -g fish_color_redirection normal
set -g fish_color_end normal
set -g fish_color_error normal
set -g fish_color_param normal
set -g fish_color_comment normal
set -g fish_color_operator normal
set -g fish_term24bit 1
set -g fish_color_normal normal --bold=off