# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "vfio-pci"
    "xhci_pci"
    "ahci"
    "nvme"
    "usb_storage"
    "usbhid"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [];
  boot.kernelModules = [
    "kvmfr"
    "vfio-pci"
    "vfio"
    "vfio_iommu_type1"
    "vfio_virqfd"
    "kvm-amd"
    "v4l2loopback"
    "i2c-dev"
    "ddcci_backlight"
  ];
  boot.extraModulePackages = with config.boot.kernelPackages; [
    v4l2loopback
    kvmfr
    ddcci-driver
  ];
  boot.extraModprobeConfig = ''
    options v4l2loopback devices=1 video_nr=1 card_label="OBS Cam" exclusive_caps=1
    options vfio-pci ids=1002:164e,1002:1640
    options vfio_iommu_type1 allow_unsafe_interrupts=1
    options kvm_amd nested=1
    options kvmfr static_size_mb=64
  '';

  services.udev.extraRules = ''
    KERNEL=="kvmfr*", MODE="0660", GROUP="kvm", OWNER="milky"
    KERNEL=="i2c-[0-9]*", GROUP="i2c", MODE="0660"
  '';
  users.groups.i2c = {};

  security.polkit.enable = true;

  boot.kernelParams = [
    "quiet"
    "splash"
    "amd_iommu=on"
    "iommu=pt"
    "vfio-pci.ids=1002:164e,1002:1640"
  ];

  powerManagement = {
    enable = true;
    cpuFreqGovernor = "performance";
  };

  hardware.graphics = {
    enable = true;
    enable32Bit = true;
  };

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/94c6d306-d0f7-4c64-bdea-41d33ba58c66";
    fsType = "btrfs";
    options = ["subvol=@" "compress=zstd"];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/94c6d306-d0f7-4c64-bdea-41d33ba58c66";
    fsType = "btrfs";
    options = ["subvol=@home" "compress=zstd"];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/94c6d306-d0f7-4c64-bdea-41d33ba58c66";
    fsType = "btrfs";
    options = ["subvol=@nix" "compress=zstd" "noatime"];
  };

  fileSystems."/mount/Rigel" = {
    device = "/dev/disk/by-uuid/00be669c-8b01-4c11-be32-50c47630a1a6";
    fsType = "btrfs";
  };

  fileSystems."/mount/Vega" = {
    device = "/dev/disk/by-uuid/534c846c-487d-4db6-be6d-ab0d5c49b612";
    fsType = "btrfs";
  };

  fileSystems."/mount/Deneb" = {
    device = "/dev/disk/by-uuid/dcf862d7-fefc-4026-aa24-70531a310e16";
    fsType = "btrfs";
  };

  fileSystems."/mount/VM" = {
    device = "/dev/disk/by-uuid/e155b7bf-82bb-4a5e-8d12-61262db0f340";
    fsType = "btrfs";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/2E94-7043";
    fsType = "vfat";
  };

  swapDevices = [
    {
      device = "/swapfile";
      size = 32 * 1024;
    }
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp13s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp12s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
